default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecotone_web_development

test:
  <<: *default
  database: ecotone_web_test

production:
  <<: *default
  database: ecotone_web_production
  username: ecotone_web
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
